### ISSUE TITLE
How to create configuration file for 2 fans?

### ISSUE THREAD

**Issue by ghost** [KastB/fancontrol#1]
Hi,
I have created a configuration file for ASUS UX32LN (2 fans):

INTERVAL=1
DEVPATH=hwmon3=devices/platform/coretemp.0 hwmon0=devices/platform/asus_fan
DEVNAME=hwmon3=coretemp hwmon0=asus_fan
FCTEMPS=hwmon0/pwm1=hwmon3/temp1_input hwmon0/pwm2=hwmon3/temp1_input
FCFANS= hwmon0/pwm1=hwmon0/fan1_input hwmon0/pwm2=hwmon0/fan2_input
MINTEMP=hwmon0/pwm1=45 hwmon0/pwm2=45
MAXTEMP=hwmon0/pwm1=85 hwmon0/pwm2=85
MINSTART=hwmon0/pwm1=35 hwmon0/pwm2=35
MINSTOP=hwmon0/pwm1=0 hwmon0/pwm2=0 

It is working great, but nethertheless I am not pleased with this solution (the NVIDIA GPU fan is controlled using the CPU temp...). Unfortunately sensors does not detect my GPU...

Do you have any ideas for improvement?

**Comment by KastB** [comment]
Hi,

I've added a temperature reading of the GPU to my asus-fan module.
It would be great if you could check if that is working, and if it is possible to control the 2nd fan with it. I don't have a dual fan notebook thus I can't check it myself.
