### ISSUE TITLE
syntax error: operand expected (error token is "/4")

### ISSUE THREAD

**Issue by user426** [KastB/fancontrol#4]
Hello when I run pwmconfig on I get the following error "line 455: let: threshold=3*/4: syntax error: operand expected (error token is "/4")"
```
Testing pwm control hwmon0/pwm1 ...
cat: hwmon3/fan1_input: Invalid argument
  hwmon0/fan1_input ... speed was 4724 now 778
    It appears that fan hwmon0/fan1_input
    is controlled by pwm hwmon0/pwm1
Would you like to generate a detailed correlation (y)? n
  hwmon0/fan2_input ... speed was 4781 now 4751
    no correlation
  hwmon0/fan3_input ... speed was 4451 now 4149
    no correlation
  hwmon3/fan1_input ... speed was  now 
/usr/bin/pwmconfig: line 455: let: threshold=3*/4: syntax error: operand expected (error token is "/4")
/usr/bin/pwmconfig: line 456: [: -lt: unary operator expected
    no correlation

```
Available for more testing

**Comment by KastB** [comment]
It seems that the speed reading for hwmon3 does not work and is thus blank.
This results in this non-number blank in the formula which is in turn a syntax error.
So the primarily error is the faulty speed reading (and no validation of the reading)
Can you try the unmodified pwmconfig from whatever your distro is?
For example: http://manpages.ubuntu.com/manpages/cosmic/man8/pwmconfig.8.html
My guess is not related to my modifications but already exists in the original upstream version.

Cheers
